In [40]:
# 转换数据
import pandas as pd
import json

# 读取 CSV 文件
df = pd.read_csv('../data/origin_data.csv')
# 去除空数据
df = df[df['data'] != '{}']

# 处理第二列数据
def expand_column(row):
    data = json.loads(row['data'])
    for key, value in data.items():
        if int(key) <= 0:
            continue
        row[key] = value
    return row

df = df.apply(expand_column, axis=1)

# 删除原始数据列
df = df.drop('data', axis=1)
df = df.drop('user_id', axis=1)

# 空数据
df = df.fillna(0)

# 保存结果
df.to_csv('../data/test_data.csv', index=False)

In [ ]:
import pandas as pd
import json
import random

df = pd.read_csv('../data/test_data.csv')

data = df.values


for num in range(10):
    for idx in range(len(data)):
        value = data[idx]
        #print("oldValue",value)
        newValue = []
        for jdx in range(len(value)):
            newValue.append(int(value[jdx]) + random.randint(0, 10000))
        #print('newValue',newValue) 
        df.loc[len(df.index)] = newValue
    print(df.values)

df.to_csv('../data/test_data1.csv', index=False)


In [52]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import colors as mcolors
import joblib

def k_means(k, data_pca):
    # 创建 KMeans 模型，并将数据聚类为k组
    kmeans = KMeans(n_clusters=k, random_state=0).fit(data_pca)

    # 获取聚类结果
    labels = kmeans.labels_

    # 获取聚类中心
    cluster_centers = kmeans.cluster_centers_

    # print("聚类结果：", labels)
    # print("聚类中心：", cluster_centers)

    score = silhouette_score(data_pca, labels)
    # print(f"Silhouette Coefficient: {score}")
    # 可视化结果
    n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
    colors = list(mcolors.TABLEAU_COLORS.values())

    for i in range(n_clusters):
        plt.scatter(data_pca[labels==i, 0], data_pca[labels==i, 1], c=colors[i])

    plt.legend()
    plt.show()
    return score


# 读取数据
df = pd.read_csv('../data/test_data.csv')
data = df.values
print('data')
print(data)

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
print('data_scaled')
print(data_scaled)

pca = PCA(n_components=2)
data_pca = pca.fit_transform(data_scaled)

# for k in range(2, 3):
#     score = k_means(k, data_pca)
#     print('k=', k, 'score=', score)

data
[[ 31703.  24591. 116859. 302925.   4256.]
 [ 59012.   1796.  88106.  47448.  13043.]
 [118025.   3593. 176212.  94897.  26087.]
 [118025.   3593. 176212.  94897.  26087.]
 [     0.   1322.  20649.  35339.   3721.]
 [118025.   3593. 176212.  94897.  26087.]]
data_scaled
[[-0.90103373  2.22188671 -0.1525839   2.15167392 -1.22817505]
 [-0.32108786 -0.56458879 -0.64835511 -0.72347564 -0.3501244 ]
 [ 0.93213803 -0.34492235  0.87080528 -0.18948247  0.95331166]
 [ 0.93213803 -0.34492235  0.87080528 -0.18948247  0.95331166]
 [-1.57429251 -0.62253086 -1.81147683 -0.85975086 -1.28163552]
 [ 0.93213803 -0.34492235  0.87080528 -0.18948247  0.95331166]]


In [ ]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors as mcolors
import joblib


keans = joblib.load('../model/kmeans_model.pkl')

df = pd.read_csv('../data/test_data.csv')
data = df.values
print(data)
df.loc[len(df.index)] = [31703, 24591,116859,302925,4256]
data = df.values
print(data)

scaler = joblib.load('../model/scaler.pkl')
pca = joblib.load('../model/pca.pkl')

data_scaled = scaler.fit_transform(data)
print('data_scaled')
print(data_scaled)

pca = PCA(n_components=2)
data_pca = pca.fit_transform(data_scaled)
print(data_pca)

for i in range(len(data_pca)):
    d = data_pca[i].reshape(1, -1)
    print("d=", d)
    s = keans.predict(d)
    print("s =", s)


In [93]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors as mcolors
import joblib


keans = joblib.load('../model/kmeans_model.pkl')

scaler = joblib.load('../model/scaler.pkl')
pca = joblib.load('../model/pca.pkl')

data = [[31703, 24591,116859,302925,4256]]

data_scaled = scaler.transform(data)
print('data_scaled')
print(data_scaled)

data_pca = pca.transform(data_scaled)
print('data_pca')
print(data_pca)

param = data_pca[0].reshape(1,-1)
print("param=", param)
s = keans.predict(param)
print("s=",s)


data_scaled
[[-0.90103373  2.22188671 -0.1525839   2.15167392 -1.22817505]]
data_pca
[[2.4502773  2.43025843]]
param= [[2.4502773  2.43025843]]
s= [1]
